package com.rigstudio.app.editor

import android.graphics.Bitmap
import android.net.Uri
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.rigstudio.app.RigStudioApplication
import com.rigstudio.app.art.TemplateArt
import com.rigstudio.app.export.ExportResult
import com.rigstudio.core.template.CharacterSheetTemplate
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

data class TemplateUiState(
    val preview: Bitmap? = null,
    val loading: Boolean = true,
    val saving: Boolean = false,
    val message: String? = null,
    val savedBytes: Long = 0L,
    val slotCount: Int = CharacterSheetTemplate.SLOTS.size,
    val requiredCount: Int = CharacterSheetTemplate.SLOTS.count { it.required },
    val sheetWidth: Int = CharacterSheetTemplate.SHEET_WIDTH,
    val sheetHeight: Int = CharacterSheetTemplate.SHEET_HEIGHT,
    val version: Int = CharacterSheetTemplate.VERSION,
) {
    val sizeLabel: String get() = "$sheetWidth × $sheetHeight px"
    val countsLabel: String get() = "$slotCount slots · $requiredCount required"
}

/**
 * The bundled blank character sheet: view it, and save it as a 2048×2048 PNG the user can draw on
 * in any painting app.
 *
 * The template is generated by RigStudio's own drawing code ([TemplateArt]) — there is no bundled
 * third-party artwork anywhere in the app.
 */
class TemplateViewModel(private val app: RigStudioApplication) : ViewModel() {

    private val templateArt: TemplateArt = app.templateArt

    private val _state = MutableStateFlow(TemplateUiState())
    val state: StateFlow<TemplateUiState> = _state.asStateFlow()

    init {
        renderPreview()
    }

    fun renderPreview() {
        viewModelScope.launch {
            _state.update { it.copy(loading = true) }
            val preview = withContext(Dispatchers.IO) {
                runCatching { templateArt.renderPreview(PREVIEW_PX) }.getOrNull()
            }
            _state.update { it.copy(preview = preview, loading = false) }
        }
    }

    /** Writes the full-size sheet to a user-chosen location (Documents UI / SAF). */
    fun saveTo(uri: Uri) {
        viewModelScope.launch {
            _state.update { it.copy(saving = true, message = null) }
            val saved = templateArt.saveSheet(uri)
            _state.update {
                it.copy(
                    saving = false,
                    savedBytes = saved.getOrDefault(0L),
                    message = saved.fold(
                        onSuccess = { bytes ->
                            "Saved ${ExportResult.formatBytes(bytes)} character sheet " +
                                "(${it.sheetWidth}×${it.sheetHeight} PNG)."
                        },
                        onFailure = { error ->
                            error.message ?: "That location could not be written to."
                        },
                    ),
                )
            }
        }
    }

    fun consumeMessage() {
        _state.update { it.copy(message = null) }
    }

    companion object {
        private const val PREVIEW_PX = 1024

        fun factory(app: RigStudioApplication): ViewModelProvider.Factory =
            object : ViewModelProvider.Factory {
                @Suppress("UNCHECKED_CAST")
                override fun <T : ViewModel> create(modelClass: Class<T>): T = TemplateViewModel(app) as T
            }
    }
}
